-- MySQL Script generated by MySQL Workbench
-- Sat Nov  3 01:29:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jsp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jsp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webticket` DEFAULT CHARACTER SET utf8 ;
USE `webticket` ;

-- -----------------------------------------------------
-- Table `webticket`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Ticket` (
  `IdTicket` INT NOT NULL,
  `IdCliente` INT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `DataCriacao` DATETIME NULL,
  `DataFechamento` DATETIME NULL,
  PRIMARY KEY (`IdTicket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Empresa` (
  `IdEmpresa` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `RazaoSocial` VARCHAR(100) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`IdEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`Operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Operador` (
  `IdOperador` INT NOT NULL,
  `IdUsuario` INT NULL,
  PRIMARY KEY (`IdOperador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Usuario` (
  `IdUsuario` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `NivelAcesso` INT NULL,
  `Status` INT NULL,
  `Operador_IdOperador` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`, `Operador_IdOperador`),
  INDEX `fk_Usuario_Operador1_idx` (`Operador_IdOperador` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Operador1`
    FOREIGN KEY (`Operador_IdOperador`)
    REFERENCES `webticket`.`Operador` (`IdOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Cliente` (
  `IdCliente` INT NOT NULL,
  `IdUsuario` INT NULL,
  `IdEmpresa` INT NULL,
  `Nome` VARCHAR(100) NULL,
  `Sobrenome` VARCHAR(100) NULL,
  `DataNascimento` VARCHAR(20) NULL,
  `Sexo` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Empresa_IdEmpresa` INT NOT NULL,
  `Usuario_IdUsuario` INT NOT NULL,
  `Usuario_Operador_IdOperador` INT NOT NULL,
  PRIMARY KEY (`IdCliente`, `Empresa_IdEmpresa`, `Usuario_IdUsuario`, `Usuario_Operador_IdOperador`),
  INDEX `fk_Cliente_Empresa1_idx` (`Empresa_IdEmpresa` ASC) VISIBLE,
  INDEX `fk_Cliente_Usuario1_idx` (`Usuario_IdUsuario` ASC, `Usuario_Operador_IdOperador` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Empresa1`
    FOREIGN KEY (`Empresa_IdEmpresa`)
    REFERENCES `webticket`.`Empresa` (`IdEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_IdUsuario` , `Usuario_Operador_IdOperador`)
    REFERENCES `webticket`.`Usuario` (`IdUsuario` , `Operador_IdOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `webticket`.`TicketConversa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`TicketConversa` (
  `IdTicketConversa` INT NOT NULL,
  `IdTicket` INT NULL,
  `IdCliente` INT NULL,
  `IdOperador` INT NULL,
  `Conteudo` VARCHAR(100) NULL,
  `DataPostagem` DATETIME NULL,
  `Ticket_IdTicket` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `Operador_IdOperador` INT NOT NULL,
  PRIMARY KEY (`Ticket_IdTicket`, `Cliente_IdCliente`, `Operador_IdOperador`),
  INDEX `fk_TicketConversa_Cliente1_idx` (`Cliente_IdCliente` ASC) VISIBLE,
  INDEX `fk_TicketConversa_Operador1_idx` (`Operador_IdOperador` ASC) VISIBLE,
  CONSTRAINT `fk_TicketConversa_Ticket`
    FOREIGN KEY (`Ticket_IdTicket`)
    REFERENCES `webticket`.`Ticket` (`IdTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TicketConversa_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `webticket`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TicketConversa_Operador1`
    FOREIGN KEY (`Operador_IdOperador`)
    REFERENCES `webticket`.`Operador` (`IdOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`Topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`Topico` (
  `IdTopico` INT NOT NULL,
  `IdCliente` INT NULL,
  `IdMelhorResposta` INT NULL,
  `Titulo` VARCHAR(100) NULL,
  `Descricao` VARCHAR(100) NULL,
  `DataCriacao` DATETIME NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `Cliente_Empresa_IdEmpresa` INT NOT NULL,
  `Cliente_Usuario_IdUsuario` INT NOT NULL,
  `Cliente_Usuario_Operador_IdOperador` INT NOT NULL,
  PRIMARY KEY (`IdTopico`, `Cliente_IdCliente`, `Cliente_Empresa_IdEmpresa`, `Cliente_Usuario_IdUsuario`, `Cliente_Usuario_Operador_IdOperador`),
  INDEX `fk_Topico_Cliente1_idx` (`Cliente_IdCliente` ASC, `Cliente_Empresa_IdEmpresa` ASC, `Cliente_Usuario_IdUsuario` ASC, `Cliente_Usuario_Operador_IdOperador` ASC) VISIBLE,
  CONSTRAINT `fk_Topico_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente` , `Cliente_Empresa_IdEmpresa` , `Cliente_Usuario_IdUsuario` , `Cliente_Usuario_Operador_IdOperador`)
    REFERENCES `webticket`.`Cliente` (`IdCliente` , `Empresa_IdEmpresa` , `Usuario_IdUsuario` , `Usuario_Operador_IdOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webticket`.`TopicoComentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webticket`.`TopicoComentario` (
  `idTopicoComentario` INT NOT NULL,
  `IdTopico` INT NULL,
  `Idusuario` INT NULL,
  `Conteudo` VARCHAR(100) NULL,
  `Votos` INT NULL,
  `DataPostagem` DATETIME NULL,
  `Topico_IdTopico` INT NOT NULL,
  `Topico_Cliente_IdCliente` INT NOT NULL,
  `Topico_Cliente_Empresa_IdEmpresa` INT NOT NULL,
  `Topico_Cliente_Usuario_IdUsuario` INT NOT NULL,
  `Topico_Cliente_Usuario_Operador_IdOperador` INT NOT NULL,
  PRIMARY KEY (`idTopicoComentario`, `Topico_IdTopico`, `Topico_Cliente_IdCliente`, `Topico_Cliente_Empresa_IdEmpresa`, `Topico_Cliente_Usuario_IdUsuario`, `Topico_Cliente_Usuario_Operador_IdOperador`),
  INDEX `fk_TopicoComentario_Topico1_idx` (`Topico_IdTopico` ASC, `Topico_Cliente_IdCliente` ASC, `Topico_Cliente_Empresa_IdEmpresa` ASC, `Topico_Cliente_Usuario_IdUsuario` ASC, `Topico_Cliente_Usuario_Operador_IdOperador` ASC) VISIBLE,
  CONSTRAINT `fk_TopicoComentario_Topico1`
    FOREIGN KEY (`Topico_IdTopico` , `Topico_Cliente_IdCliente` , `Topico_Cliente_Empresa_IdEmpresa` , `Topico_Cliente_Usuario_IdUsuario` , `Topico_Cliente_Usuario_Operador_IdOperador`)
    REFERENCES `webticket`.`Topico` (`IdTopico` , `Cliente_IdCliente` , `Cliente_Empresa_IdEmpresa` , `Cliente_Usuario_IdUsuario` , `Cliente_Usuario_Operador_IdOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
